import './Studentslide.css';
import React from 'react';

function Studentslide5() {
  return (
    <div class="body">
      <div class="sslide6">
        <p>
        Radiation is commonly delivered as high-energy <em>X-rays</em>, also called <em>photons</em>
        <br></br>
        <br></br>
        X-rays are generated by a machine known as a <em>linear accelerator</em>, or <em>LINAC</em>
        </p>
        <img class="sslide5_image" src="sslide5_machine.jpg"/>
      </div>
    </div>
  );
}
  
export default Studentslide5;
